name: barras
description: A simple and customizable barcode scanning package for Android and iOS. It uses AVCaptureSession in iOS and ZXing in Android.
version: 0.2.1
homepage: https://github.com/deadblit/barras

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.10.5"

dependencies:
  flutter:
    sdk: flutter

  qrcode_forked: ^1.0.2
  torch_controller: ^2.0.1
  flutter_beep:
    git:
      url: https://github.com/jhonathanqz/flutter_beep
      ref: master 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
